set(ARCBUILD_ROOT_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(ARCBUILD_DIR "${ARCBUILD_ROOT_DIR}/arcbuild")

if(_BUILD)
  unset(_BUILD)
  include(${ARCBUILD_DIR}/build.cmake)
  arcbuild_build()
else()
  include(${ARCBUILD_DIR}/core.cmake)
endif()
