include(${ARCBUILD_DIR}/core.cmake)

arcbuild_get_cmake_argv(argv)
list(FIND argv "-P" ret)
if(ret EQUAL -1)
  unset(argv)
  unset(ret)
  include(${ARCBUILD_DIR}/core.cmake)
else()
  unset(argv)
  unset(ret)
  include(${ARCBUILD_DIR}/build.cmake)
  arcbuild_build()
endif()
